# Generated by Django 5.2.14 on 2026-05-25 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement Export'), ('utility_electricity', 'Utility Electricity Bill Export'), ('corporate_travel', 'Corporate Travel API Sync')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source_reference', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('activity_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement Export'), ('utility_electricity', 'Utility Electricity Bill Export'), ('corporate_travel', 'Corporate Travel API Sync')], max_length=50)),
                ('scope_category', models.IntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Indirect'), (3, 'Scope 3 - Value Chain')])),
                ('activity_type', models.CharField(max_length=100)),
                ('facility_or_plant', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField()),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('calculated_co2e', models.DecimalField(decimal_places=4, max_digits=18)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('suspicious', 'Suspicious'), ('failed', 'Failed')], default='valid', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.company')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='core.rawrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('file', 'File Upload'), ('api', 'API Sync')], default='file', max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.datasource')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.rawupload'),
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.normalizedemissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Sustainability Analyst'), ('auditor', 'ESG Auditor'), ('admin', 'Administrator')], default='analyst', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('error', 'Error (Fails Record)'), ('warning', 'Warning (Suspicious)')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.normalizedemissionrecord')),
            ],
        ),
    ]
